AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/**/*'
  NewCops: enable

Metrics/MethodLength:
  Max: 30

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
